language: php
sudo: false

php:
  - 7.1
  - 7.2

cache:
  directories:
    - build/.composer-cache

before_install:
  - export COMPOSER_CACHE_DIR="$(pwd)/build/.composer-cache"
  - export XDEBUG="/home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini"
  - mv -v "$XDEBUG" "$XDEBUG.disabled"

install:
  - mkdir -p build/php_codesniffer build/php-cs-fixer
  - composer require --no-suggest --no-progress -n -a -d build/php-cs-fixer "friendsofphp/php-cs-fixer:^2.12"
  - composer require --no-suggest --no-progress -n -a -d build/php_codesniffer "squizlabs/php_codesniffer:^3.3"
  - composer update --no-suggest --no-progress -n -a

script:
  - build/php_codesniffer/vendor/bin/phpcs -p --standard=PSR2 src
  - build/php-cs-fixer/vendor/bin/php-cs-fixer fix -v --dry-run --allow-risky=yes --using-cache=no
